### PR TITLE
SYNC-1282

### PR DESCRIPTION
**Pull request by dejuknow**

### CODE REVIEW

**Comment by dejuknow** [comment]
Can you try this and see what you think?

- The "name" and "description" in the popup are pretty redundant. Should we make the description super descriptive like, "Site members will be able to view and add discussion to files uploaded by the Liferay Sync client"

- I left it as "Default File Permissions" instead of "Define Default File Permissions" since it follows the pattern of having just "Permissions" as opposed to "Define Permissions" in the action button.

**Comment by shinnlok** [comment]
@dejuknow Did you build this against 6.2? It's not compiling for me.

**Comment by dejuknow** [comment]
I developed on 6.2, but it compiles for me fine on trunk. Loading the Sync Admin page does give me an NPE when loading the JSP, but this happens even on master currently for me.

**Comment by shinnlok** [comment]
K got it working.. your suggestions seem to be the way to go.

**Pull request closed without merging**
